version: '3'

services:
  #Node Service
  avalon-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: avalon/node
    container_name: avalon-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - avalon-network
    command: npm run start:dev
    ports:
      - 3000:3000

  #Nginx Service
  avalon-webserver:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: avalon-nginx
    depends_on:
      - avalon-app
    restart: unless-stopped
    tty: true
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=localhost
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    expose:
      - 80
    ports:
      - 80:80

  #MongoDb Service
  avalon-db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    tty: true
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mongo/
    networks:
      - avalon-network

#Docker Networks
networks:
  avalon-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
